#ifndef HCI_H
#define	HCI_H

#include "l2cap.h"

enum OGF_CODES {
	OGF_LINK_CONTROL = 0x01,
	OGF_LINK_POLICY = 0x02,
	OGF_CONTROLLER_BASEBAND = 0x03,
	OGF_INFORMATIONAL_PARAMETERS = 0x04,
	OGF_STATUS_PARAMETERS = 0x05,
	OGF_VENDOR_SPECIFIC = 0x3F
};

enum OCF_LINK_CONTROL_CODES {
	HCI_INQUIRY = 0x01,
	HCI_INQUIRY_CANCEL = 0x02,
	HCI_PERIODIC_INQUIRY_MODE = 0x03,
	HCI_EXIT_PERIODIC_INQUIRY_MODE = 0x04,
	HCI_CREATE_CONNECTION = 0x05,
	HCI_DISCONNECT = 0x06,
	HCI_CREATE_CONNECTION_CANCEL = 0x08,
	HCI_ACCEPT_CONNECTION_REQUEST = 0x09,
	HCI_REJECT_CONNECTION_REQUEST = 0x0A,
	HCI_LINK_KEY_REQUEST_REPLY = 0x0B,
	HCI_LINK_KEY_REQUEST_NEGATIVE_REPLY = 0x0C,
	HCI_PIN_CODE_REQUEST_REPLY = 0x0D,
	HCI_PIN_CODE_REQUEST_NEGATIVE_REPLY = 0x0E,
	HCI_CHANGE_CONNECTION_PACKET_TYPE = 0x0F,
	HCI_AUTHENTICATION_REQUESTED = 0x11,
	HCI_SET_CONNECTION_ENCRYPTION = 0x13,
	HCI_CHANGE_CONNECTION_LINK_KEY = 0x15,
	HCI_MASTER_LINK_KEY = 0x17,
	HCI_REMOTE_NAME_REQUEST = 0x19,
	HCI_REMOTE_NAME_REQUEST_CANCEL = 0x1A,
	HCI_READ_REMOTE_SUPPORTED_FEATURES = 0x1B,
	HCI_READ_REMOTE_EXTENDED_FEATURES = 0x1C,
	HCI_READ_REMOTE_VERSION_INFORMATION = 0x1D,
	HCI_READ_CLOCK_OFFSET = 0x1F,
	HCI_READ_LMP_HANDLE = 0x20,
	HCI_SETUP_SYNCHRONOUS_CONNECTION = 0x28,
	HCI_ACCEPT_SYNCHRONOUS_CONNECTION_REQUEST = 0x29,
	HCI_REJECT_SYNCHRONOUS_CONNECTION_REQUEST = 0x2A,
	HCI_IO_CAPABILITY_REQUEST_REPLY = 0x2B,
	HCI_USER_CONFIRMATION_REQUEST_REPLY = 0x2C,
	HCI_USER_CONFIRMATION_REQUEST_NEGATIVE_REPLY = 0x2D,
	HCI_USER_PASSKEY_REQUEST_REPLY = 0x2E,
	HCI_USER_PASSKEY_REQUEST_NEGATIVE_REPLY = 0x2F,
	HCI_REMOTE_OOB_DATA_REQUEST_REPLY = 0x30,
	HCI_REMOTE_OOB_DATA_REQUEST_NEGATIVE_REPLY = 0x33,
	HCI_IO_CAPABILITY_REQUEST_NEGATIVE_REPLY = 0x34,
	HCI_CREATE_PHYSICAL_LINK = 0x35,
	HCI_ACCEPT_PHYSICAL_LINK = 0x36,
	HCI_DISCONNECT_PHYSICAL_LINK = 0x37,
	HCI_CREATE_LOGICAL_LINK = 0x38,
	HCI_ACCEPT_LOGICAL_LINK = 0x39,
	HCI_DISCONNECT_LOGICAL_LINK = 0x3A,
	HCI_LOGICAL_LINK_CANCEL = 0x3B,
	HCI_FLOW_SPEC_MODIFY = 0x3C,
	HCI_ENHANCED_SETUP_SYNCHRONOUS_CONNECTION = 0x3D,
	HCI_ENHANCED_ACCEPT_SYNCHRONOUS_CONNECTION_REQUEST = 0x3E,
	HCI_TRUNCATED_PAGE = 0x3F,
	HCI_TRUNCATED_PAGE_CANCEL = 0x40,
	HCI_SET_CONNECTIONLESS_SLAVE_BROADCAST = 0x41,
	HCI_SET_CONNECTIONLESS_SLAVE_BROADCAST_RECEIVE = 0x42,
	HCI_START_SYNCHRONIZATION_TRAIN = 0x43,
	HCI_RECEIVE_SYNCHRONIZATION_TRAIN = 0x44,
	HCI_REMOTE_OOB_EXTENDED_DATA_REQUEST_REPLY = 0x45
};

enum OCF_LINK_POLICY_CODES {
	HCI_HOLD_MODE = 0x01,
	HCI_SNIFF_MODE = 0x03,
	HCI_EXIT_SNIFF_MODE = 0x04,
	HCI_QOS_SETUP = 0x07,
	HCI_ROLE_DISCOVERY = 0x09,
	HCI_SWITCH_ROLE = 0x0B,
	HCI_READ_LINK_POLICY_SETTINGS = 0x0C,
	HCI_WRITE_LINK_POLICY_SETTINGS = 0x0D,
	HCI_READ_DEFAULT_LINK_POLICY_SETTINGS = 0x0E,
	HCI_WRITE_DEFAULT_LINK_POLICY_SETTINGS = 0x0F,
	HCI_FLOW_SPECIFICATION = 0x10
	//HCI_SNIFF_SUBRATING = 0x11
};

enum OCF_CONTROLLER_BASEBAND_CODES {
	HCI_SET_EVENT_MASK = 0x01,
	HCI_RESET = 0x03,
	HCI_SET_EVENT_FILTER = 0x05,
	HCI_FLUSH = 0x08,
	HCI_READ_PIN_TYPE = 0x09,
	HCI_WRITE_PIN_TYPE = 0x0A,
	HCI_READ_STORED_LINK_KEY = 0x0D,
	HCI_WRITE_STORED_LINK_KEY = 0x11,
	HCI_DELETE_STORED_LINK_KEY = 0X12,
	HCI_WRITE_LOCAL_NAME = 0x13,
	HCI_READ_LOCAL_NAME = 0x14,
	HCI_READ_CONNECTION_ACCEPT_TIMEOUT = 0x15,
	HCI_WRITE_CONNECTION_ACCEPT_TIMEOUT = 0x16,
	HCI_READ_PAGE_TIMEOUT = 0x17,
	HCI_WRITE_PAGE_TIMEOUT = 0x18,
	HCI_READ_SCAN_ENABLE = 0x19,
	HCI_WRITE_SCAN_ENABLE = 0x1A,
	HCI_READ_PAGE_SCAN_ACTIVITY = 0x1B,
	HCI_WRITE_PAGE_SCAN_ACTIVITY = 0x1C,
	HCI_READ_INQUIRY_SCAN_ACTIVITY = 0x1D,
	HCI_WRITE_INQUIRY_SCAN_ACTIVITY = 0x1E,
	HCI_READ_AUTHENTICATION_ENABLE = 0x1F,
	HCI_WRITE_AUTHENTICATION_ENABLE = 0x20,
	HCI_READ_CLASS_OF_DEVICE = 0x23,
	HCI_WRITE_CLASS_OF_DEVICE = 0x24,
	HCI_READ_VOICE_SETTING = 0x25,
	HCI_WRITE_VOICE_SETTING = 0x26,
	HCI_READ_AUTOMATIC_FLUSH_TIMEOUT = 0x27,
	HCI_WRITE_AUTOMATIC_FLUSH_TIMEOUT = 0x28,
	HCI_READ_NUM_BROADCAST_RETRANSMISSIONS = 0x29,
	HCI_WRITE_NUM_BROADCAST_RETRANSMISSIONS = 0x2A,
	HCI_READ_HOLD_MODE_ACTIVITY = 0x2B,
	HCI_WRITE_HOLD_MODE_ACTIVITY = 0x2C,
	HCI_READ_TRANSMIT_POWER_LEVEL = 0x2D,
	HCI_READ_SYNCHRONOUS_FLOW_CONTROL_ENABLE = 0x2E,
	HCI_WRITE_SYNCHRONOUS_FLOW_CONTROL_ENABLE = 0x2F,
	HCI_SET_CONTROLLER_TO_HOST_FLOW_CONTROL = 0x31,
	HCI_HOST_BUFFER_SIZE = 0x33,
	HCI_HOST_NUMBER_OF_COMPLETED_PACKETS = 0x35,
	HCI_READ_LINK_SUPERVISION_TIMEOUT = 0x36,
	HCI_WRITE_LINK_SUPERVISION_TIMEOUT = 0x37,
	HCI_READ_NUMBER_OF_SUPPORTED_IAC = 0x38,
	HCI_READ_CURRENT_IAC_LAP = 0x39,
	HCI_WRITE_INQUIRY_SCAN_TYPE = 0x43,
	HCI_WRITE_INQUIRY_MODE = 0x45,
	HCI_READ_PAGE_SCAN_TYPE = 0x46,
	HCI_WRITE_PAGE_SCAN_TYPE = 0x47,
	HCI_READ_AFH_CHANNEL_ASSESSMENT_MODE = 0x48,
	HCI_WRITE_AFH_CHANNEL_ASSESSMENT_MODE = 0x49,
	HCI_READ_EXTENDED_INQUIRY_RESPONSE = 0x51,
	HCI_WRITE_EXTENDED_INQUIRY_RESPONSE = 0x52,
	HCI_REFRESH_ENCRYPTION_KEY = 0x53,
	HCI_READ_SIMPLE_PAIRING_MODE = 0x55,
	HCI_WRITE_SIMPLE_PAIRING_MODE = 0x56,
	HCI_READ_LOCAL_OOB_DATA = 0x57,
	HCI_READ_INQUIRY_RESPONSE_TRANSMIT_POWER_LEVEL = 0x58,
	HCI_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL = 0x59,
	HCI_READ_DEFAULT_ERRONEOUS_DATA_REPORTING = 0x5A,
	HCI_WRITE_DEFAULT_ERRONEOUS_DATA_REPORTING = 0x5B,
	HCI_ENHANCED_FLUSH = 0x5F,
	HCI_SEND_KEYPRESS_NOTIFICATION = 0x60,
	HCI_READ_LOGICAL_LINK_ACCEPT_TIMEOUT = 0x61,
	HCI_WRITE_LOGICAL_LINK_ACCEPT_TIMEOUT=  0x62,
	HCI_SET_EVENT_MASK_PAGE_2 = 0x63,
	HCI_READ_LOCATION_DATA = 0x64,
	HCI_WRITE_LOCATION_DATA = 0x65,
	HCI_READ_GLOW_CONTROL_MODE = 0x66,
	HCI_WRITE_FLOW_CONTROL_MODE = 0x67,
	HCI_READ_ENHANCED_TRANSMIT_POWER_LEVEL = 0x68,
	HCI_READ_BEST_EFFORT_FLUSH_TIMEOUT = 0x69,
	HCI_WRITE_BEST_EFFORT_FLUSH_TIMEOUT = 0x6A,
	HCI_SHORT_RANGE_MODE = 0x6B,
	HCI_READ_LE_HOST_SUPPORT = 0x6C,
	HCI_WRITE_LE_HOST_SUPPORTED = 0x6D,
	HCI_SET_MWS_CHANNEL_PARAMETERS = 0x6E,
	HCI_SET_EXTERNAL_FRAME_CONFIGURATION = 0x6F,
	HCI_SET_MWS_SIGNALING = 0x70,
	HCI_SET_MWS_TRANSPORT_LAYER = 0x71,
	HCI_SET_MWS_SCAN_FREQUENCY_TABLE = 0x72,
	HCI_SET_MWS_PATTERN_CONFIGURATION = 0x73,
	HCI_SET_RESERVED_LT_ADDR = 0x74,
	HCI_DELETE_RESERVED_LT_ADDR = 0x75,
	HCI_SET_CONNECTIONLESS_SLAVE_BROADCAST_DATA = 0x76,
	HCI_READ_SYNCHRONIZATION_TRAIN_PARAMETERS = 0x77,
	HCI_WRITE_SYNCHRONIZATION_TRAIN_PARAMETERS = 0x78,
	HCI_READ_SECURE_CONNECTIONS_HOST_SUPPORT = 0x79,
	HCI_WRITE_SECURE_CONNECTIONS_HOST_SUPPORT = 0x7A,
	HCI_READ_AUTHENTICATED_PAYLOAD_TIMEOUT = 0x7B,
	HCI_WRITE_AUTHENTICATED_PAYLOAD_TIMEOUT = 0x7C,
	HCI_READ_LOCAL_OOB_EXTENDED_DATA = 0x7D,
	HCI_READ_EXTENDED_PAGE_TIMEOUT = 0x7E,
	HCI_WRITE_EXTENDED_PAGE_TIMEOUT = 0x7F,
	HCI_READ_EXTENDED_INQUIRY_LENGTH = 0x80,
	HCI_WRITE_EXTENDED_INQUIRY_LENGTH = 0x81
};

enum OCF_INFORMATIONAL_PARAMETER_CODES {
	HCI_READ_LOCAL_VERSION_INFORMATION = 0x01,
	HCI_READ_LOCAL_SUPPORTED_COMMANDS = 0x02,
	HCI_READ_LOCAL_SUPPORTED_FEATURES = 0x03,
	HCI_READ_LOCAL_EXTENDED_FEATURES = 0x04,
	HCI_READ_BUFFER_SIZE = 0x05,
	HCI_READ_BD_ADDR = 0x09,
	HCI_READ_DATA_BLOCK_SIZE = 0x0A,
	HCI_READ_LOCAL_SUPPORTED_CODECS = 0x0B,
	HCI_READ_LOCAL_SIMPLE_PAIRING_OPTIONS = 0x0C
};

enum HCI_EVENTS {
	HCI_INQUIRY_COMPLETE = 0x01,
	HCI_INQUIRY_RESULT = 0x02,
	HCI_CONNECTION_COMPLETE = 0x03,
	HCI_CONNECTION_REQUEST = 0x04,
	HCI_DISCONNECTION_COMPLETE = 0x05,
	HCI_AUTHENTICATION_COMPLETE = 0x06,
	HCI_REMOTE_NAME_REQUEST_COMPLETE = 0x07,
	HCI_ENCRYPTION_CHANGE = 0x08,
	HCI_CHANGE_CONNECTION_LINK_KEY_COMPLETE = 0x09,
	HCI_MASTER_LINK_KEY_COMPLETE = 0x0A,
	HCI_READ_REMOTE_SUPPORTED_FEATURES_COMPLETE = 0x0B,
	HCI_READ_REMOTE_VERSION_INFORMATION_COMPLETE = 0x0C,
	HCI_QOS_SETUP_COMPLETE = 0x0D,
	HCI_COMMAND_COMPLETE = 0x0E,
	HCI_COMMAND_STATUS = 0x0F,
	HCI_HARDWARE_ERROR = 0x10,
	HCI_FLUSH_OCCURRED = 0x11,
	HCI_ROLE_CHANGE = 0x12,
	HCI_NUMBER_OF_COMPLETED_PACKETS = 0x13,
	HCI_MODE_CHANGE = 0x14,
	HCI_RETURN_LINK_KEYS = 0x15,
	HCI_PIN_CODE_REQUEST = 0x16,
	HCI_LINK_KEY_REQUEST = 0x17,
	HCI_LINK_KEY_NOTIFICATION = 0x18,
	HCI_LOOPBACK_COMMAND = 0x19,
	HCI_DATA_BUFFER_OVERFLOW = 0x1A,
	HCI_MAX_SLOTS_CHANGE = 0x1B,
	HCI_READ_CLOCK_OFFSET_COMPLETE = 0x1C,
	HCI_CONNECTION_PACKET_TYPE_CHANGED = 0x1D,
	HCI_QOS_VIOLATION = 0x1E,
	HCI_PAGE_SCAN_REPETITION_MODE_CHANGE = 0x20,
	HCI_FLOW_SPECIFICATION_COMPLETE = 0x21,
	HCI_INQUIRY_RESULT_WITH_RSSI = 0x22,
	HCI_READ_REMOTE_EXTENDED_FEATURES_COMPLETE = 0x23,
	HCI_SYNCHRONOUS_CONNECTION_COMPLETE = 0x2C,
	HCI_SYNCHRONOUS_CONNECTION_CHANGED = 0x2D,
	HCI_SNIFF_SUBRATING = 0x2E,
	HCI_EXTENDED_INQUIRY_RESULT = 0x2F,
	HCI_ENCRYPTION_KEY_REFRESH_COMPLETE = 0x30,
	HCI_IO_CAPABILITY_REQUEST = 0x31,
	HCI_IO_CAPABILITY_RESPONSE = 0x32,
	HCI_USER_CONFIRMATION_REQUEST = 0x33,
	HCI_USER_PASSKEY_REQUEST = 0x34,
	HCI_REMOTE_OOB_DATA_REQUEST = 0x35,
	HCI_SIMPLE_PAIRING_COMPLETE = 0x36,
	HCI_LINK_SUPERVISION_TIMEOUT_CHANGED = 0x38,
	HCI_ENHANCED_FLUSH_COMPLETE = 0x39,
	HCI_USER_PASSKEY_NOTIFICATION = 0x3B,
	HCI_KEYPRESS_NOTIFICATION = 0x3C,
	HCI_REMOTE_HOST_SUPPORTED_FEATURES_NOTIFICATION = 0x3D,
	HCI_LE_CONNECTION_COMPLETE = 0x3E,
	HCI_PHYSICAL_LINK_COMPLETE = 0x40,
	HCI_CHANNEL_SELECTED = 0x41,
	HCI_DISCONNECTION_PHYSICAL_LINK_COMPLETE = 0x42,
	HCI_PHYSICAL_LINK_LOSS_EARLY_WARNING = 0x43,
	HCI_PHYSICAL_LINK_RECOVERY = 0x44,
	HCI_LOGICAL_LINK_COMPLETE = 0x45,
	HCI_DISCONNECTION_LOGICAL_LINK_COMPLETE = 0x46,
	HCI_FLOW_SPEC_MODIFY_COMPLETE = 0x47,
	HCI_NUMBER_OF_COMPLETED_DATA_BLOCKS = 0x48,
	HCI_AMP_START_TEST = 0x49,
	HCI_AMP_TEST_END = 0x4A,
	HCI_AMP_RECEIVER_REPORT = 0x4B,
	HCI_SHORT_RANGE_MODE_CHANGE_COMPLETE = 0x4C,
	HCI_AMP_STATUS_CHANGE = 0x4D,
	HCI_TRIGGERED_CLOCK_CAPTURE = 0x4E,
	HCI_SYNCHRONIZATION_TRAIN_COMPLETE = 0x4F,
	HCI_SYNCHRONIZATION_TRAIN_RECEIVED = 0x50,
	HCI_CONNECTIONLESS_SLAVE_BROADCAST_RECEIVE = 0x51,
	HCI_CONNECTIONLESS_SLAVE_BROADCAST_TIMEOUT = 0x52,
	HCI_TRUNCATED_PAGE_COMPLETE = 0x53,
	HCI_SLAVE_PAGE_RESPONSE_TIMEOUT = 0x54,
	HCI_CONNECTIONLESS_SLAVE_BROADCAST_CHANNEL_MAP_CHANGE = 0x55,
	HCI_INQUIRY_RESPONSE_NOTIFICATION = 0x56,
	HCI_AUTHENTICATED_PAYLOAD_TIMEOUT_EXPIRED = 0x57,
	HCI_SAM_STATUS_CHANGE = 0x58
};

struct hci_evt {
	uint8_t code;
	uint8_t param_len;
	uint8_t data[];
} __attribute__((packed));

struct hci_evt_cmd_complete {
	uint8_t allowed_pkts;
	uint16_t opcode;
	uint8_t data[];
} __attribute__((packed));

struct hci_evt_cmd_status {
	uint8_t status;
	uint8_t allowed_pkts;
	uint16_t opcode;
} __attribute__((packed));

struct hci_cmd {
	uint16_t opcode;  //little endian
	uint8_t param_len;
	uint8_t data[253];
} __attribute__((packed));

struct hci_acl {
	uint16_t handle : 12;  //little endian
	uint8_t packet_boundary : 2;
	uint8_t broadcast : 2;

	uint16_t data_len;

	uint8_t data[];
} __attribute__((packed));

struct hci_connection {
	bool active;
	uint16_t handle;
	const uint8_t * addr;
	
	uint16_t data_packets_flushed;
	
	uint8_t l2cap_recv[64];
	int32_t l2cap_recv_len;
	uint8_t l2cap_send[132];
	int32_t l2cap_send_len;
	int32_t l2cap_send_offset;
	
	uint8_t l2cap_cmd_queue[L2CAP_CMD_QUEUE_SIZE];		// Store pending event codes
	uint8_t l2cap_cmd_queue_cid[L2CAP_CMD_QUEUE_SIZE];	// Store CID associated with queued command
	uint8_t l2cap_cmd_queue_id[L2CAP_CMD_QUEUE_SIZE];	// Store ID associated with queued command (responses only)
	uint8_t l2cap_cmd_queue_pos;
	uint8_t l2cap_cmd_queue_num;

	struct l2cap_connection connections[NUM_L2CAP_CHANNELS];
};

#define MAX_HCI_CONNECTIONS 4
#define HCI_EVT_QUEUE_SIZE 32

extern uint8_t hci_reset_status;

void hci_reset();
uint8_t hci_get_connectable_status();
struct hci_connection * hci_get_connection_from_handle(uint16_t handle);
void hci_queue_evt(uint8_t evt, uint16_t opcode, uint16_t handle);

uint8_t * hci_get_cmd_buffer();
void hci_recv_command(int32_t len);
int32_t hci_get_event(uint8_t * buf);

void hci_recv_data(uint8_t * buf, int32_t len);
int32_t hci_get_data(uint8_t * buf);

#endif	/* HCI_H */
